{% set version = "0.1-12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tiff
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tiff_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tiff/tiff_{{ version }}.tar.gz
  sha256: df10ce719f92597572763182f7cb03686b8d7fb9123d036a4daf5b10738e815c

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - libtiff                      # [not win]
  run:
    - r-base

test:
  commands:
    - $R -e "library('tiff')"           # [not win]
    - "\"%R%\" -e \"library('tiff')\""  # [win]

about:
  home: http://www.rforge.net/tiff/
  license: GPL-2.0-or-later
  summary: This package provides an easy and simple way to read, write and display bitmap images stored in the TIFF format. It can read and write both files and in-memory raw vectors.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
