appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: mp1BemclaZkppm2rsSRGxeWZ2hR/mfXS3uZOv1+BQVkrTuQlF4xKMiwMaCKL0LbpqzWOsDGF94bMuKYtGy8HQOr/Z+VXTW0vUsJWiRI98suq6ONfmM1dbhtHgICFdugF37Thq7xA6T35UO11O2UG2FKLoskr02xhfgcQbqxkyHh5D183OA0g6KLwcM4H921YcrQvNcTIKPp+P/rUtph+Bt08/+ip2xeSgI9wQOFOgFzTcxscqcdMP0TNhe6pBy0beNHm9vpmHRQ1Lyz6itHi31dzSZTCGIv73zMAfbg/FmPnkgdOKTTnb2X6km2k0EQorCAktpxDL/7w8h5G7RCAFT+fOjFkZC2zuim6mRozdZnIpkdDAZjEIqlQsDJXKFfM7PTMtRCVDhWwpHq3IYyyO/DMLfI/1imTn6NnNhnZDZApsXKARQmvHvnf3ctzwBJ7A2jEopPQz86O3W9uFCI89tj7HI2kAmRuNvQVrRVTRck3ZpAdna55Nhg1aAt+TNGiR5LrdrTiMWIgU9MJWc5jYUZVBAuRz0RekWuhxseG6OiBVw2uRUz0rAuzFSfulyo+WuqLEIU5tXs5676FOQg8FNAo7Ewn7kud/JrbRwTFQbEpDGg7jPmyfBZkR7LKyFrkruf6amazfMQccyKjbgoKzToRJAk9sDvr+Ilu5+LEml4=}
bot:
  automerge: true
