travis:
  secure:
    BINSTAR_TOKEN: t3qBVtqFr8CUSgb4YnRVJO/HCEtwbtx/zhaOtkaMLQvMFgHp9BiWp6ngMR5sQOPBDeqv3s5/kS07Ell+SJlQDT6QnlhHZUqQX5WaGZeT0cXDEh7aWO8FYyNqdbkUjKhIUxZp6oOwsYCMo0WZhqj/fmjOY9wo/PQ/L/ex6UbdjmbzR7+jgbO599fE2+sUE3Qq3jmwXFQd7blkNcMWBMGT9sWIeAhf0D1UyTRAfzre3E8vcTHCa4gXlCCZ6u3vuF4RUryYOldIFA8xJiUgmMTeych183YYWFRppiHM82SxMqjJKLhwQsURAcH20o86tQF12dwQxEs5B3K/aBv8eYMSrcgdIDlY6SCXNxVTHvCgVu7LVzbCi/FeRrmbxNJQQsalBf81LOC8bmgwldT5I3T8+ZOWSQS6ss8yJLNWm9C5BAGHnedrE5cMSQCYKXU9eEVBmyYMkvyMG8trlFaSExjrWC/H38FPSBEf8C778a0jlHxtauHrmFJ3SZPgojkAhqcYqi1Vo/14pFEkeSK8HtFkbH4m9Bw8Emf8jGllrNKN/vKp6ockUU4+vsOKhSh5XziV7/Rl7Ksy3suO2D3UPIiXjQMImLdiO2HPBN2SQWpYHlcc3Plc/HIWxKHSajtx6jZLB1CR61Og99x9+aXBH0wokb6Vk4ZZSLWxTUOgS9lD18Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
